### ISSUE TITLE
Color change doesnt work

### ISSUE THREAD

**Issue by wag-bsw** [bruegmann/themify-2#61]
When you change the color with the colorpicker, the value does not change

**Comment by nku-bsw** [comment]
The CSS in `ThemesHome.tsx` in the `jsVarToSass() ` function is getting passed incorrectly.
 - To correctly pass the value you will need change the output in ThemesHome.tsx Line 168: `output = JSON.parse(localStorage.getItem("css") as any).cssOutput + getComment() + bluevar;`

**Comment by nku-bsw** [comment]
Done in #67
